### ISSUE TITLE
No response from the display

### ISSUE THREAD

**Issue by johnrees** [topherCantrell/ER-OLEDM032-1#1]
Thanks for sharing this code. I was wondering if you could take a quick look at my connections just so I am sure I've not made a stupid mistake! The script itself is running fine on the pi, but nothing is happening on the OLED screen.

I used the same wire colours as your schematic

![image](https://cloud.githubusercontent.com/assets/601961/6618202/c74fb17a-c8b8-11e4-96c6-a7c10948eb8a.png)
![image](https://cloud.githubusercontent.com/assets/601961/6618204/cc75a218-c8b8-11e4-8dc9-d1030d80d66e.png)

Is the ground cable correct?
![image](https://cloud.githubusercontent.com/assets/601961/6618205/d0613e0a-c8b8-11e4-8053-c3dd83303be8.png)

Jumpers, I had to move mine like you did too -
![image](https://cloud.githubusercontent.com/assets/601961/6618244/2c6c8740-c8b9-11e4-9b47-1f85f96409ec.png)

I haven't got a multimeter but I will try and get hold of one this week.

Thanks!

**Comment by johnrees** [comment]
Glancing through the code it looks like my ground wiring is at fault as nothing is connected to GPIO 25. I'll have another shot at it

**Comment by topherCantrell** [comment]
Keep me posted! I was just getting ready to dive in!

**Comment by johnrees** [comment]
Oh thank you! I've been trying! Still no luck. I now have a common ground and my pinouts match your diagram exactly. I've just got 2 pins floating/disconnected pins on the display just like it shows. My jumpers are connecting R19 and R21

![img_0144](https://cloud.githubusercontent.com/assets/601961/6625421/deb94b4e-c8e7-11e4-9ad9-c919edea6154.JPG)
![img_0145](https://cloud.githubusercontent.com/assets/601961/6625422/deb97e70-c8e7-11e4-9790-bbce4eca02d0.JPG)
![img_0146](https://cloud.githubusercontent.com/assets/601961/6625423/debc66da-c8e7-11e4-8a7b-eefcffd4b1b1.JPG)

I'm starting to give up hope to be honest, it's so frustrating when it shows no sign of life.

I tried disconnecting the OLED display from its board and connecting a second, identical board-less display to it but that isn't working either. I think I probably have a bad board but without an oscilloscope or any debugging tools I'm at a loss.

The only thing I could think of was touching the ground leg of a regular LED connected to the 5V source to various points where I'd expect ground on the board to check that the soldering was OK. All of the ground pins and the jumper connections were lighting the LED so that seemed alright. Hmm..

**Comment by topherCantrell** [comment]
Don't give up hope! You've already done the hard part with the wiring
harness.

It looks like you are using the Pi2, which has more I/O pins than the Pi I
am using.

If you slide all your wires at the bottom up 7 pins you'll match the old pi
(the one in my diagram). I am attaching a picture of your GPIO connector
with a red box showing mine. Try that change and let me know!

Sorry to just get back to you. Been a long week.

[image: Inline image 1]

**Comment by johnrees** [comment]
Yesss!!! You have no idea how happy this has made me! I **can't believe** I overlooked the number of pins. What was I thinking?! Thank you thank you thank you.

![unnamed](https://cloud.githubusercontent.com/assets/601961/6656962/3e32d458-cb33-11e4-8f0c-e66dec976ac0.jpg)

Now to get onto the fun task of making some animations of it! I'll keep you posted with progress

**Comment by johnrees** [comment]
![unnamed 1](https://cloud.githubusercontent.com/assets/601961/6657003/e6363536-cb34-11e4-9cbb-39a0976befba.jpg)
haha

**Comment by topherCantrell** [comment]
HAHAHA! That last photo makes me smile! Please do keep me posted on your
fun!
