### ISSUE TITLE
Unkown commands 0xB4 and 0xD1

### ISSUE THREAD

**Issue by Amomum** [topherCantrell/ER-OLEDM032-1#3]
It's not an issue per se, more like a question. I wasn't able to find this commands in the datasheet, however they are used in the example code (without explanation), and you continue to use them:

``` python
def Initial():
   <..>
    Write_Instruction(0xB4) <-- # here
    Write_Data(0xA0)
    Write_Data(0xfd) 
    Write_Instruction(0xC1) # set contrast current  
    Write_Data(Contrast_level)
    Write_Instruction(0xC7) # master contrast current control 
    Write_Data(0x0f)
     
    Write_Instruction(0xB1) # SET PHASE LENGTH
    Write_Data(0xE2)
    Write_Instruction(0xD1) <-- # and here
    Write_Data(0x82)
    Write_Data(0x20) 
```

so I'm wondering if by any chance you have worked out what these commands do?

**Comment by topherCantrell** [comment]
I think this is a perfect use of the issues. Thanks for the question. I did some digging and found an updated PDF datasheet. I uploaded it to my repo in docs. It explains those commands.

**Comment by Amomum** [comment]
Oh my god, where did you get it?! I searched the whole internet with no success! Thank you so much!
