### ISSUE TITLE
Magic offset of X coordinate

### ISSUE THREAD

**Issue by Amomum** [topherCantrell/ER-OLEDM032-1#4]
Again, not an issue, more of a question.

There is a function:

``` python
def set_data_window(self,x,y,width,height):
    
    x = int(x / 4) # Column address is 4-pixel-groups (2 bytes)
              # Pass in x=0,4,8, etc
              
    width = int(width / 4) # With limited to 4-pixel increments
                      # Pass in width=4,8, etc
    
    self.Write_Instruction(0x75)
    self.Write_Data(y)
    self.Write_Data(y+height-1)
    
    self.Write_Instruction(0x15) 
    self.Write_Data(0x1C+x)            <<<<
    self.Write_Data(0x1C+x+width-1)    <<<<
```
for some unexplained reason there is an additional offset `0x1C` that is added to the X coordinates (i.e. column address).

I'm aware that this offset got here from the example code (where it's not explained either); but maybe you know why is it required?

**Comment by topherCantrell** [comment]
The only thing I can think of is that the driver will work for up to
480x128 p;ixels. This offset must be how the 256x64 is wired
